### ISSUE TITLE
Starting the built .msi file is not possible from inside VS.

### ISSUE THREAD

**Issue by ghost** [firegiant/HeatWaveSupport#52] opened 2023-12-13 03:40 UTC
### HeatWave Version

1.0.2.1

### What's your idea?

For me, an IDE is a software to write and debug software. Unfortunately, I can't execute the built .msi from inside devenv.exe by using the <F5> key to start debugging. Also, <Ctrl+F5> is not available.
So for me, you didn't implement a working solution for devenv.exe.

**Comment by robmen** [comment] 2023-12-13 04:25
Duplicate of #11

**Closed as not planned by robmen** 2023-12-13 04:25 UTC
Labels: triage
