### ISSUE TITLE
UpToDateCheckImplicitConfiguredInputDataSource error after VS 17.5.0 update

### ISSUE THREAD

**Issue by Retik** [firegiant/HeatWaveSupport#23] opened 2023-02-21 23:03 UTC
### HeatWave Version

0.9.4

### Visual Studio Version

17.5.0

### Repro Steps

1. Create new Wix v4 MSI Project
2. Add a project reference (custom actions) to the wixproj

### Actual Result

VS displays an error banner at the top saying, "Visual Studio ran into an expected problem with one or more projects. You may need to reload affected proejcts or the solution to prevent further problems."
Additionally, the MSI project has a red X icon over it.

Exception from VsProjectFault log
=====================
2/21/2023 2:57:49 PM
LimitedFunctionality
System.AggregateException: Project system data flow 'UpToDateCheckImplicitConfiguredInputDataSource: 60693278' closed because of an exception.
The given key 'TargetPath' was not present in the dictionary. ---> System.Collections.Generic.KeyNotFoundException: The given key 'TargetPath' was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Microsoft.VisualStudio.ProjectSystem.UpToDate.UpToDateCheckImplicitConfiguredInput.<>c__DisplayClass76_0.<Update>g__UpdateCopyData|7()
   at Microsoft.VisualStudio.ProjectSystem.UpToDate.UpToDateCheckImplicitConfiguredInput.Update(IProjectSubscriptionUpdate jointRuleUpdate, IProjectSubscriptionUpdate sourceItemsUpdate, IProjectItemSchema projectItemSchema, IProjectCatalogSnapshot projectCatalogSnapshot)
   at Microsoft.VisualStudio.ProjectSystem.UpToDate.UpToDateCheckImplicitConfiguredInputDataSource.<>c__DisplayClass8_0.<<LinkExternalInput>g__TransformAsync|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformBlockSlimAsync.<ProcessInputAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.<ProcessInputQueueAsync>d__5.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Collections.Generic.KeyNotFoundException: The given key 'TargetPath' was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Microsoft.VisualStudio.ProjectSystem.UpToDate.UpToDateCheckImplicitConfiguredInput.<>c__DisplayClass76_0.<Update>g__UpdateCopyData|7()
   at Microsoft.VisualStudio.ProjectSystem.UpToDate.UpToDateCheckImplicitConfiguredInput.Update(IProjectSubscriptionUpdate jointRuleUpdate, IProjectSubscriptionUpdate sourceItemsUpdate, IProjectItemSchema projectItemSchema, IProjectCatalogSnapshot projectCatalogSnapshot)
   at Microsoft.VisualStudio.ProjectSystem.UpToDate.UpToDateCheckImplicitConfiguredInputDataSource.<>c__DisplayClass8_0.<<LinkExternalInput>g__TransformAsync|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformBlockSlimAsync.<ProcessInputAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.<ProcessInputQueueAsync>d__5.MoveNext()<---

### Expected Result

Wix project should not have a red X and there should be no error banner.

**Comment by FireGiantHelp** [comment] 2023-02-23 21:21
We can reproduce this internally. It seems to be an issue in the Visual Studio project system. We are working with the Visual Studio team to understand what is failing.

**Comment by FireGiantHelp** [comment] 2023-02-25 06:34
We expect this issue is fixed in HeatWave v0.9.5 now available in Visual Studio Marketplace so Visual Studio should provide notification of the update.

**Closed by FireGiantHelp** 2023-02-25 06:34 UTC
Labels: bug
