### ISSUE TITLE
Build events does not expand all project variables

### ISSUE THREAD

**Issue by tholp** [firegiant/HeatWaveSupport#46] opened 2023-11-03 09:55 UTC
### HeatWave Version

1.0.2

### Visual Studio Version

16.11.31

### Repro Steps

Write a Pre-Build event command line that contains (e.g.,) the variable `$(ProjectDir)`  this variable will expand to _nothing_.
The variable `$(DevEnvDir)` on the other hand does expand to the expected string.

```
echo $(ProjectDir)
echo $(DevEnvDir)
```

### Actual Result

```
1>ECHO is on.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\
```

### Expected Result

```
1>C:\...
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\
```

**Comment by chrpai** [comment] 2023-11-16 14:12
https://github.com/wixtoolset/issues/issues/7866

This appears to be a Heatwave bug, an SDK targets bug, or a misalignment between the two. If I author a postbuild it puts it in the primary property group. For console app sdk project type it authors it as:

```
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy /y &quot;$(TargetPath)&quot; C:\GitHub" />
  </Target>
```
  
If I move this to the .wixproj msbuild processes it correctly but HeatWave doesn't see it in the property designer.

**Comment by FireGiantHelp** [comment] 2024-01-14 04:58
Duplicate of #44

**Closed as not planned by FireGiantHelp** 2024-01-14 04:58 UTC
Labels: duplicate
