### ISSUE TITLE
Create a new project doesn't work, errors out with HRESULT 0x80041fe4

### ISSUE THREAD

**Issue by BPodszun** [firegiant/HeatWaveSupport#22] opened 2023-02-13 09:49 UTC
### HeatWave Version

0.9.4.1

### Visual Studio Version

17.4.4

### Repro Steps

1.  Open VS, click "Create a new project"
2.  Select "MSI package (WiX v4)"
3.  Fill in a project name and click "Create"

### Actual Result

A message box appears, saying

---------------------------
Microsoft Visual Studio
---------------------------
Exception from HRESULT: 0x80041FE1
---------------------------
OK   
---------------------------

And nothing else happens/the project and solution isn't created and I'm stuck.

### Expected Result

I expected to be able to generate a new project

**Comment by FireGiantHelp** [comment] 2023-02-23 21:15
We've been unable to reproduce this issue. Can you send the ActivityLog.xml in the `%APPDATA%\Microsoft\VisualStudio\17.0_xxxxxxx\` folder? That is the first and easiest place to start.

**Comment by BPodszun** [comment] 2023-02-24 04:18
This is resolved. My current understanding is that my VS was lacking features and this is either not checked in a nice way during installation of the HeatWave addon or during the project creation phase.

What I did:
* Install a (naked, bare) VS Community for HeatWave - I'm a VS Code person otherwise so this was brand new
* Run the above and receive the cryptic failure message
* File this bug report
* Grab some example WiX projects from https://github.com/kurtanr/WiXInstallerExamples.git
* Open the project in VS. VS complains about missing features both for C# and C++ (for their custom action examples)
* Install said features and migrate projects to WiX4. Things work

Since then I can create new projects as well. So ultimately it's on me, but if there's a way to make this problem more obvious on your side that might help the first impression in similar cases?

**Comment by FireGiantHelp** [comment] 2023-02-24 18:55
Thanks for that additional information.  With that in hand, we were able to reproduce the issue starting from a fresh VM, just as you described.  And you are correct that we need to declare additional prereqs and have them enforced on install.  We've taken a first pass at addressing this with the HeatWave 0.9.5 release due out later today.

**Comment by FireGiantHelp** [comment] 2023-03-24 16:50
We expect this issue is fixed in HeatWave v0.9.6 now available in Visual Studio Marketplace so Visual Studio should provide notification of the update.

**Closed by FireGiantHelp** 2023-03-24 16:50 UTC
Labels: bug

**Comment by levaconline** [comment] 2023-12-09 15:13
![image](https://github.com/firegiant/HeatWaveSupport/assets/5190586/ea58db85-3f84-41a0-861f-7dd44c41b7b7)
